### ISSUE TITLE
Add conversation handler to make admin commands easier to use

### ISSUE THREAD

**Issue by Elias-YJ** [fyysikkokilta/vaalilakanabot#3]
Using this [exampe](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/conversationbot.py), make the admin commands such that when using `/lisaa` or `/poista`, the user starts a discussion: 
1. The bot asks to choose the role from all options
2. When answer is selected, the bot asks the user to input the name of the applicant.
3. If name and role are matched in the database, conversation is ended
4. Otherwise, give options to end conversation or return to step 1

**Comment by Jaakkonen** [comment]
Seems to be done based on projects and commits. Closing. Feel free to re-open if appropriate.
